accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginView, name='login'),
    path('logout_view', views.logout_view, name='logout_view')
]

whatsapp_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from chats.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include(('accounts.urls', 'accounts'),)),

    path('', index, name='home'),
    path('chat/<str:username>/', chatPage, name='chat'),

    path('create_group/',create_group, name='create_group'),
    path('group_chat/<str:group_name>/',group_chat, name='group_chat'),

]

accounts/models.py
from django.db import models

# Create your models here.

chats/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileModel(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    name = models.CharField(blank=True, null=True, max_length=100)
    online_status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.username


class GroupChat(models.Model):
    group_name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def __str__(self) -> str:
        return self.group_name
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class SignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Username"
        self.fields['email'].label = ""
        self.fields['password1'].label = ""
        self.fields['password2'].label = ""
        self.fields['username'].widget.attrs.update(
            {'class': 'myfieldclass form-control'})
        self.fields['email'].widget.attrs.update(
            {'class': 'myfieldclass form-control'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'myfieldclass form-control'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'myfieldclass form-control'})

        # giving place holders to fields
        self.fields['username'].widget.attrs.update(
            {'placeholder': 'Enter Your Username*'})
        self.fields['email'].widget.attrs.update(
            {'placeholder': 'Enter Your Email*'})
        self.fields['password1'].widget.attrs.update(
            {'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'placeholder': 'Confirm Password'})

        for text in ['username', 'password1', 'password2']:
            self.fields[text].help_text = None

accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

User = get_user_model()


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)

            return HttpResponseRedirect(reverse('home'))

    else:
        form = SignUpForm()

    return render(request, 'accounts/register.html', {'form': form})    


def loginView(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home'))

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Account Not Active")
        else:
            context = {'notfound': True}
            print(
                f"NO ACCOUNT FOUND WITH USERNAME {username} AND PASSWORD {password}")
            print(context)
            return render(request, 'accounts/login.html', context)

    else:
        return render(request, 'accounts/login.html')
                                                                                                                                                                                                                                                                    
@login_required
def logout_view(request):
    logout(request)
    return redirect('/')    

chats/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model

from django.contrib.auth.models import User
from .models import GroupChat
from firebase_admin import db

from django.contrib.auth.decorators import login_required

User = get_user_model()

@login_required
# Create your views here.
def index(request):
    user = request.user
    user = User.objects.filter(username=user.username)
    user_groups = GroupChat.objects.filter(users__in=user)


    users = User.objects.exclude(username=request.user.username)
    return render(request, 'index.html', context={'users': users, 'user_groups': user_groups})

@login_required
def chatPage(request, username):
    
    user = request.user
    user = User.objects.filter(username=user.username)
    user_groups = GroupChat.objects.filter(users__in=user)

    user_obj = User.objects.get(username=username)  
    users = User.objects.exclude(username=request.user.username)
    
    if request.user.id > user_obj.id:
        thread_name = f'chat_{request.user.id}-{user_obj.id}'
    else:
        thread_name = f'chat_{user_obj.id}-{request.user.id}'

    db_ref = db.reference('/messages')

    query_result = db_ref.order_by_child('thread_name').equal_to(thread_name).get()

    message_objs = []
    for message_id, message_data in query_result.items():
        message_objs.append({
            'sender': message_data['sender'],
            'message': message_data['message'],
        })

    return render(request, 'main_chat.html', context={'user': user_obj, 'users': users, 'messages': message_objs, 'user_groups':user_groups})

@login_required
def create_group(request):
    participants = User.objects.all().exclude(id=request.user.id)
    
    if request.method == 'POST':
        group_name = request.POST['group_name']
        selected_participant_ids = request.POST.getlist('participants')

        new_group = GroupChat.objects.create(group_name=group_name)
        new_group.users.set(selected_participant_ids)
       
        return redirect('/') 
    
    return render(request, 'create_group.html', {'participants': participants})


@login_required
def group_chat(request, group_name):

    current_user = request.user
    user = User.objects.filter(username=current_user.username)
    user_groups =  GroupChat.objects.filter(users__in=user)
    
    selected_group = GroupChat.objects.get(group_name=group_name)
    
    users = User.objects.exclude(username=current_user.username)
    
    message_objs = []
    thread_name = f'group_chat_{selected_group.id}'
    
    if thread_name:
        db_ref = db.reference('/messages')
        query_result = db_ref.order_by_child('thread_name').equal_to(thread_name).get()

        for message_id, message_data in query_result.items():
            message_objs.append({
                'sender': message_data['sender'],
                'message': message_data['message'],
            })

    return render(request, 'group_chat.html', context={
        'current_user': current_user,
        'user_groups': user_groups,
        'selected_group': selected_group,
        'users': users,
        'messages': message_objs,
    })

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:300);

    .login-page {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
    }

    .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 360px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }

    .form input {
        font-family: "Roboto", sans-serif;
        outline: 0;
        background: #f2f2f2;
        width: 100%;
        border: 0;
        margin: 0 0 15px;
        padding: 15px;
        box-sizing: border-box;
        font-size: 14px;
    }

    .form button {
        font-family: "Roboto", sans-serif;
        text-transform: uppercase;
        outline: 0;
        background: #7e867e;
        width: 100%;
        border: 0;
        padding: 15px;
        color: #FFFFFF;
        font-size: 14px;
        -webkit-transition: all 0.3 ease;
        transition: all 0.3 ease;
        cursor: pointer;
    }

    .form button:hover,
    .form button:active,
    .form button:focus {
        background: #43A047;
    }

    .form .message {
        margin: 15px 0 0;
        color: #b3b3b3;
        font-size: 12px;
    }

    .form .message a {
        color: #4CAF50;
        text-decoration: none;
    }

    .form .register-form {
        display: none;
    }

    .container {
        position: relative;
        z-index: 1;
        max-width: 300px;
        margin: 0 auto;
    }

    .container:before,
    .container:after {
        content: "";
        display: block;
        clear: both;
    }

    .container .info {
        margin: 50px auto;
        text-align: center;
    }

    .container .info h1 {
        margin: 0 0 15px;
        padding: 0;
        font-size: 36px;
        font-weight: 300;
        color: #1a1a1a;
    }

    .container .info span {
        color: #4d4d4d;
        font-size: 12px;
    }

    .container .info span a {
        color: #000000;
        text-decoration: none;
    }

    .container .info span .fa {
        color: #EF3B3A;
    }

    body {
        background: #656565;
       
    }
</style>

<div class="login-page">
    <div class="form">
        <form class="login-form" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="username" name="username" />
            <input type="password" placeholder="password" name="password" />
            <button>login</button>
            <p class="message">Not registered? <a href="{% url 'accounts:register' %}">Create an account</a></p>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" />
    {% block css %}{% endblock %}
</head>
<body> 
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}
</body>

</html>

templates/create_group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CREATE GROUP</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="group_name">Group Name:</label>
        <input type="text" name="group_name" id="group_name">
        
        <p>Choose your favorite users to add to this group:</p>
        <ul>
            {% for participant in participants %}
                <li>
                    <input type="checkbox" name="participants" value="{{participant.id}}"> {{participant.username}}
                </li>
            {% endfor %}
        </ul>
        
        <input type="submit" value="Create Group">
    </form>
</body>
</html>

templates/demo.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

	<frameset rows = "20%, 60%, 20%">
		<frame name = "top" src = "attr1.png" />
		<frame name = "main" src = "gradient3.png" />
		<frame name = "bottom" src = "col_last.png" />
		<noframes><body>The browser you are working does not support frames.</body></noframes>
	</frameset>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Group : {{group.group_name}}</title>
</head>
<body>
    {% for user in group.users.all %}
        <ul>
            <a href="#" >{{forloop.counter}} :: {{user.username}}<br>
        </ul>
    {% endfor %}
</body>
</html>

templates/group_chat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}WhatsApp{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row chat-top">
            <div class="col-sm-4 border-right border-secondary">
                <img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{request.user.username}}</span>
                <span class="float-right mt-2">
                    <div class="notification">
                        <i class="fa fa-bell-o" aria-hidden="true"></i>
                        <span class="badge" id="count_badge"></span>
                    </div>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-left-fill mx-3"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                    </svg>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mr-2"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                    </svg>
                </span>


            </div>
            <div class="col-sm-8">
                <img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                
                <span class="ml-2">{{selected_group}}</span>
                <span class="float-right mt-2">
                    {% comment %} <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                        <path fill-rule="evenodd"
                            d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                    </svg>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical mx-3"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                    </svg> {% endcomment %}
                    <a href="{% url 'accounts:logout_view' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                          <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                        </svg>
                      </a>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                {% if user.userprofilemodel.online_status %}
                                <td><a style="color: green" id="{{user.username}}_status" href="{% url 'chat' username=user.username %}">{{user.username}}</a></td>
                                {% else %}
                                <td><a style="color: grey" id="{{user.username}}_status" href="{% url 'chat' username=user.username %}">{{user.username}}</a></td>
                                {% endif %}
                            </tr>
                            {% endfor %}

                            {% for group_name in user_groups %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url 'group_chat' group_name.group_name %}">{{group_name.group_name}}</a></td>
                            </tr>
                            {% endfor %}
                            <!-- end -->
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-sm-8 message-area">
                <div class="message-table-scroll">
                    <table class="table">
                        <tbody id='chat-body'>
                            {% for message in messages %}
                            {% if message.sender == request.user.username %}
                            <tr>
                                <td>
                                    <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded">
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>
                                    <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded">
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row message-box p-3">
                    <div class="col-sm-2 mt-2">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-smile" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd"
                                d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683z" />
                            <path
                                d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip mx-2"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z" />
                        </svg>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M15 4H1v8h14V4zM1 3a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H1z" />
                            <path
                                d="M13 4a2 2 0 0 0 2 2V4h-2zM3 4a2 2 0 0 1-2 2V4h2zm10 8a2 2 0 0 1 2-2v2h-2zM3 12a2 2 0 0 0-2-2v2h2zm7-4a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" />
                        </svg>
                    </div>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="message_input" placeholder="Write message...">

                    </div>
                    <div class="col-sm-2 mt-1">
                        <div class="control">
                            <button class="btn btn-success" id="chat-message-submit">Submit</button>
                        </div>
                    </div>ss
                </div>
            </div>
        </div>
    </div>
</div>

{{selected_group.id|json_script:"json-username"}}
{{selected_group.group_name|json_script:"json-username-receiver"}}
{{request.user.username|json_script:"json-message-username"}}

<script>
    const group_id = JSON.parse(document.getElementById('json-username').textContent);
    const loggedin_user = JSON.parse(document.getElementById('json-message-username').textContent);
    const group_name = JSON.parse(document.getElementById('json-username-receiver').textContent);

    const group_socket = new WebSocket('ws://' + window.location.host + '/ws/group/' + group_id + '/');

    group_socket.onopen = function(e){
        console.log("CONNECTION ESTABLISHED");
    }

    group_socket.onclose = function(e){
        console.log("CONNECTION LOST");
    }

    group_socket.onerror = function(e){
        console.log("ERROR OCCURED");
    }
    
    group_socket.onmessage = function(e){
        const data = JSON.parse(e.data);
        const messageContainer = document.querySelector('#chat-body');

        if (data.username ==loggedin_user) {
            messageContainer.insertAdjacentHTML('beforeend', `<tr><td><p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded">${data.message}</p></td></tr>`);
        } else {
            messageContainer.insertAdjacentHTML('beforeend', `<tr><td><p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded">${data.message}</p></td></tr>`);
        }
    }

    document.querySelector('#chat-message-submit').onclick = function(e){
        const message_input = document.querySelector('#message_input');
        const message = message_input.value;

        group_socket.send(JSON.stringify({
            'message':message,
            'username':loggedin_user,
            'receiver':group_name
        }));

        message_input.value = '';
    }

</script>

{% endblock %}
{% block javascript %}
<script src="{% static 'js/online_status.js' %}"></script>
<script src="{% static 'js/notify.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}WhatsApp{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url 'chat' username=user.username %}">{{user.username}}</a></td>
                            </tr>
                            {% endfor %}
                            {% for group_name in user_groups %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url 'group_chat' group_name %}">{{group_name.group_name}}</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
<h1 href="{% url 'accounts:login' %}">>please Login here</h1>
<h1 href="{% url 'accounts:login' %}">>please Login here</h1>
<h1 href="{% url 'accounts:register' %}">>if you have not account: Register here</h1>
    